import tkinter as tk
from tkinter import messagebox
from playsound import playsound
import os
import time

class SholatGUI:
    def __init__(self, root):
        self.root = root
        self.root.title("Tuntunan Sholat Subuh")
        self.root.geometry("400x235")
        
        self.takbir_path = os.path.join('D:/Tugas Besar', 'Takbir.mp3')
        self.alfatihah_path = os.path.join('D:/Tugas Besar', 'Al-Fatihah.mp3')
        self.alikhlas_path = os.path.join('D:/Tugas Besar', 'Al-Ikhlas.mp3')
        self.alkafirun_path = os.path.join('D:/Tugas Besar', 'Al-Kafirun.mp3')
        self.sami_path = os.path.join('D:/Tugas Besar', 'Sami.mp3')
        self.takbir_sujud_path = os.path.join('D:/Tugas Besar', 'Takbir.mp3')
        self.tahiyyat1_path = os.path.join('D:/Tugas Besar', 'Tahiyyat1.mp3')
        self.tahiyyat2_path = os.path.join('D:/Tugas Besar', 'Tahiyyat2.mp3')
        self.salam_path = os.path.join('D:/Tugas Besar', 'Salam.mp3')

        self.button_subuh = tk.Button(self.root, text="Sholat Subuh", command=self.subuh_prayer)
        self.button_dzuhur = tk.Button(self.root, text="Sholat Dzuhur", command=self.dzuhur_prayer)
        self.button_ashar = tk.Button(self.root, text="Sholat Ashar", command=self.ashar_prayer)
        self.button_maghrib = tk.Button(self.root, text="Sholat Maghrib", command=self.maghrib_prayer)
        self.button_isya = tk.Button(self.root, text="Sholat Isya", command=self.isya_prayer)

        self.button_subuh.pack(pady=10)
        self.button_dzuhur.pack(pady=10)
        self.button_ashar.pack(pady=10)
        self.button_maghrib.pack(pady=10)
        self.button_isya.pack(pady=10)



    def subuh_prayer(self):
        messagebox.showinfo("Tuntunan Sholat Subuh", "Ikuti tuntunan sholat secara tertib dan berurutan.")
        playsound(os.path.join('D:/Tugas Besar', 'Warning_Subuh.mp3'))

        self.root.after(0, self.play_takbir)
        self.root.after(5000, self.play_alfatihah)
        self.root.after(8000, self.play_alikhlas)
        self.root.after(11000, self.play_ruku)
        self.root.after(14000, self.pause_3s)
        self.root.after(17000, self.play_sami)
        self.root.after(20000, self.pause_3s)
        self.root.after(23000, self.play_sujud)
        self.root.after(26000, self.pause_3s)
        self.root.after(29000, self.play_duduk)
        self.root.after(32000, self.pause_3s)
        self.root.after(35000, self.play_sujud)
        self.root.after(38000, self.pause_3s)
        self.root.after(41000, self.play_bangkit)
        self.root.after(44000, self.play_alfatihah)
        self.root.after(47000, self.play_alkafirun)
        self.root.after(50000, self.play_ruku)
        self.root.after(53000, self.pause_3s)
        self.root.after(56000, self.play_sami)
        self.root.after(59000, self.pause_3s)
        self.root.after(62000, self.play_sujud)
        self.root.after(65000, self.pause_3s)
        self.root.after(68000, self.play_duduk)
        self.root.after(71000, self.pause_3s)
        self.root.after(74000, self.play_sujud)
        self.root.after(77000, self.pause_3s)
        self.root.after(80000, self.play_bangkit)
        self.root.after(83000, self.play_tahiyyat2)
        self.root.after(86000, self.play_salam)

    def dzuhur_prayer(self):
        messagebox.showinfo("Tuntunan Sholat Dzuhur", "Ikuti tuntunan sholat secara tertib dan berurutan.")
        playsound(os.path.join('D:/Tugas Besar', 'Warning_Dzuhur.mp3'))

        self.root.after(0, self.play_takbir)
        self.root.after(5000, self.play_alfatihah)
        self.root.after(8000, self.play_alikhlas)
        self.root.after(11000, self.play_ruku)
        self.root.after(14000, self.pause_3s)
        self.root.after(17000, self.play_sami)
        self.root.after(20000, self.pause_3s)
        self.root.after(23000, self.play_sujud)
        self.root.after(26000, self.pause_3s)
        self.root.after(29000, self.play_duduk)
        self.root.after(32000, self.pause_3s)
        self.root.after(35000, self.play_sujud)
        self.root.after(38000, self.pause_3s)
        self.root.after(41000, self.play_bangkit)
        self.root.after(44000, self.play_alfatihah)
        self.root.after(47000, self.play_alkafirun)
        self.root.after(50000, self.play_ruku)
        self.root.after(53000, self.pause_3s)
        self.root.after(56000, self.play_sami)
        self.root.after(59000, self.pause_3s)
        self.root.after(62000, self.play_sujud)
        self.root.after(65000, self.pause_3s)
        self.root.after(68000, self.play_duduk)
        self.root.after(71000, self.pause_3s)
        self.root.after(74000, self.play_sujud)
        self.root.after(77000, self.pause_3s)
        self.root.after(80000, self.play_bangkit)
        self.root.after(83000, self.play_tahiyyat1)
        self.root.after(86000, self.play_takbir)
        self.root.after(89000, self.pause_30s)
        self.root.after(92000, self.play_ruku)
        self.root.after(95000, self.pause_3s)
        self.root.after(98000, self.play_sami)
        self.root.after(101000, self.pause_3s)
        self.root.after(104000, self.play_sujud)
        self.root.after(107000, self.pause_3s)
        self.root.after(110000, self.play_duduk)
        self.root.after(113000, self.pause_3s)
        self.root.after(116000, self.play_sujud)
        self.root.after(119000, self.pause_3s)
        self.root.after(122000, self.play_bangkit)
        self.root.after(125000, self.pause_30s)
        self.root.after(128000, self.play_ruku)
        self.root.after(131000, self.pause_3s)
        self.root.after(134000, self.play_sami)
        self.root.after(137000, self.pause_3s)
        self.root.after(140000, self.play_sujud)
        self.root.after(143000, self.pause_3s)
        self.root.after(146000, self.play_duduk)
        self.root.after(149000, self.pause_3s)
        self.root.after(152000, self.play_sujud)
        self.root.after(155000, self.pause_3s)
        self.root.after(158000, self.play_bangkit)
        self.root.after(161000, self.play_tahiyyat2)
        self.root.after(163000, self.play_salam)

    def ashar_prayer(self):
        messagebox.showinfo("Tuntunan Sholat Ashar", "Ikuti tuntunan sholat secara tertib dan berurutan.")
        playsound(os.path.join('D:/Tugas Besar', 'Warning_Ashar.mp3'))

        self.root.after(0, self.play_takbir)
        self.root.after(5000, self.play_alfatihah)
        self.root.after(8000, self.play_alikhlas)
        self.root.after(11000, self.play_ruku)
        self.root.after(14000, self.pause_3s)
        self.root.after(17000, self.play_sami)
        self.root.after(20000, self.pause_3s)
        self.root.after(23000, self.play_sujud)
        self.root.after(26000, self.pause_3s)
        self.root.after(29000, self.play_duduk)
        self.root.after(32000, self.pause_3s)
        self.root.after(35000, self.play_sujud)
        self.root.after(38000, self.pause_3s)
        self.root.after(41000, self.play_bangkit)
        self.root.after(44000, self.play_alfatihah)
        self.root.after(47000, self.play_alkafirun)
        self.root.after(50000, self.play_ruku)
        self.root.after(53000, self.pause_3s)
        self.root.after(56000, self.play_sami)
        self.root.after(59000, self.pause_3s)
        self.root.after(62000, self.play_sujud)
        self.root.after(65000, self.pause_3s)
        self.root.after(68000, self.play_duduk)
        self.root.after(71000, self.pause_3s)
        self.root.after(74000, self.play_sujud)
        self.root.after(77000, self.pause_3s)
        self.root.after(80000, self.play_bangkit)
        self.root.after(83000, self.play_tahiyyat1)
        self.root.after(86000, self.play_takbir)
        self.root.after(89000, self.pause_30s)
        self.root.after(92000, self.play_ruku)
        self.root.after(95000, self.pause_3s)
        self.root.after(98000, self.play_sami)
        self.root.after(101000, self.pause_3s)
        self.root.after(104000, self.play_sujud)
        self.root.after(107000, self.pause_3s)
        self.root.after(110000, self.play_duduk)
        self.root.after(113000, self.pause_3s)
        self.root.after(116000, self.play_sujud)
        self.root.after(119000, self.pause_3s)
        self.root.after(122000, self.play_bangkit)
        self.root.after(125000, self.pause_30s)
        self.root.after(128000, self.play_ruku)
        self.root.after(131000, self.pause_3s)
        self.root.after(134000, self.play_sami)
        self.root.after(137000, self.pause_3s)
        self.root.after(140000, self.play_sujud)
        self.root.after(143000, self.pause_3s)
        self.root.after(146000, self.play_duduk)
        self.root.after(149000, self.pause_3s)
        self.root.after(152000, self.play_sujud)
        self.root.after(155000, self.pause_3s)
        self.root.after(158000, self.play_bangkit)
        self.root.after(161000, self.play_tahiyyat2)
        self.root.after(163000, self.play_salam)

    def maghrib_prayer(self):
        messagebox.showinfo("Tuntunan Sholat Maghrib", "Ikuti tuntunan sholat secara tertib dan berurutan.")
        playsound(os.path.join('D:/Tugas Besar', 'Warning_Maghrib.mp3'))

        self.root.after(0, self.play_takbir)
        self.root.after(5000, self.play_alfatihah)
        self.root.after(8000, self.play_alikhlas)
        self.root.after(11000, self.play_ruku)
        self.root.after(14000, self.pause_3s)
        self.root.after(17000, self.play_sami)
        self.root.after(20000, self.pause_3s)
        self.root.after(23000, self.play_sujud)
        self.root.after(26000, self.pause_3s)
        self.root.after(29000, self.play_duduk)
        self.root.after(32000, self.pause_3s)
        self.root.after(35000, self.play_sujud)
        self.root.after(38000, self.pause_3s)
        self.root.after(41000, self.play_bangkit)
        self.root.after(44000, self.play_alfatihah)
        self.root.after(47000, self.play_alkafirun)
        self.root.after(50000, self.play_ruku)
        self.root.after(53000, self.pause_3s)
        self.root.after(56000, self.play_sami)
        self.root.after(59000, self.pause_3s)
        self.root.after(62000, self.play_sujud)
        self.root.after(65000, self.pause_3s)
        self.root.after(68000, self.play_duduk)
        self.root.after(71000, self.pause_3s)
        self.root.after(74000, self.play_sujud)
        self.root.after(77000, self.pause_3s)
        self.root.after(80000, self.play_bangkit)
        self.root.after(83000, self.play_tahiyyat1)
        self.root.after(86000, self.play_takbir)
        self.root.after(89000, self.pause_30s)
        self.root.after(92000, self.play_ruku)
        self.root.after(95000, self.pause_3s)
        self.root.after(98000, self.play_sami)
        self.root.after(101000, self.pause_3s)
        self.root.after(104000, self.play_sujud)
        self.root.after(107000, self.pause_3s)
        self.root.after(110000, self.play_duduk)
        self.root.after(113000, self.pause_3s)
        self.root.after(116000, self.play_sujud)
        self.root.after(119000, self.pause_3s)
        self.root.after(122000, self.play_bangkit)
        self.root.after(125000, self.play_tahiyyat2)
        self.root.after(128000, self.play_salam)

    def isya_prayer(self):
        messagebox.showinfo("Tuntunan Sholat Isya", "Ikuti tuntunan sholat secara tertib dan berurutan.")
        playsound(os.path.join('D:/Tugas Besar', 'Warning_Isya.mp3'))

        self.root.after(0, self.play_takbir)
        self.root.after(5000, self.play_alfatihah)
        self.root.after(8000, self.play_alikhlas)
        self.root.after(11000, self.play_ruku)
        self.root.after(14000, self.pause_3s)
        self.root.after(17000, self.play_sami)
        self.root.after(20000, self.pause_3s)
        self.root.after(23000, self.play_sujud)
        self.root.after(26000, self.pause_3s)
        self.root.after(29000, self.play_duduk)
        self.root.after(32000, self.pause_3s)
        self.root.after(35000, self.play_sujud)
        self.root.after(38000, self.pause_3s)
        self.root.after(41000, self.play_bangkit)
        self.root.after(44000, self.play_alfatihah)
        self.root.after(47000, self.play_alkafirun)
        self.root.after(50000, self.play_ruku)
        self.root.after(53000, self.pause_3s)
        self.root.after(56000, self.play_sami)
        self.root.after(59000, self.pause_3s)
        self.root.after(62000, self.play_sujud)
        self.root.after(65000, self.pause_3s)
        self.root.after(68000, self.play_duduk)
        self.root.after(71000, self.pause_3s)
        self.root.after(74000, self.play_sujud)
        self.root.after(77000, self.pause_3s)
        self.root.after(80000, self.play_bangkit)
        self.root.after(83000, self.play_tahiyyat1)
        self.root.after(86000, self.play_takbir)
        self.root.after(89000, self.pause_30s)
        self.root.after(92000, self.play_ruku)
        self.root.after(95000, self.pause_3s)
        self.root.after(98000, self.play_sami)
        self.root.after(101000, self.pause_3s)
        self.root.after(104000, self.play_sujud)
        self.root.after(107000, self.pause_3s)
        self.root.after(110000, self.play_duduk)
        self.root.after(113000, self.pause_3s)
        self.root.after(116000, self.play_sujud)
        self.root.after(119000, self.pause_3s)
        self.root.after(122000, self.play_bangkit)
        self.root.after(125000, self.pause_30s)
        self.root.after(128000, self.play_ruku)
        self.root.after(131000, self.pause_3s)
        self.root.after(134000, self.play_sami)
        self.root.after(137000, self.pause_3s)
        self.root.after(140000, self.play_sujud)
        self.root.after(143000, self.pause_3s)
        self.root.after(146000, self.play_duduk)
        self.root.after(149000, self.pause_3s)
        self.root.after(152000, self.play_sujud)
        self.root.after(155000, self.pause_3s)
        self.root.after(158000, self.play_bangkit)
        self.root.after(161000, self.play_tahiyyat2)
        self.root.after(163000, self.play_salam)

    def play_takbir(self):
        playsound(self.takbir_path)

    def play_alfatihah(self):
        playsound(self.alfatihah_path)

    def play_alikhlas(self):
        playsound(self.alikhlas_path)

    def play_alkafirun(self):
        playsound(self.alkafirun_path)

    def play_ruku(self):
        playsound(self.takbir_sujud_path)

    def pause_3s(self):
        time.sleep(3)

    def play_sami(self):
        playsound(self.sami_path)

    def play_sujud(self):
        playsound(self.takbir_sujud_path)

    def play_duduk(self):
        playsound(self.takbir_sujud_path)

    def play_bangkit(self):
        playsound(self.takbir_sujud_path)

    def play_tahiyyat1(self):
        playsound(self.tahiyyat1_path)

    def play_tahiyyat2(self):
        playsound(self.tahiyyat2_path)

    def play_salam(self):
        playsound(self.salam_path)

    def pause_30s(self):
        time.sleep(30)

if __name__ == "__main__":
    root = tk.Tk()
    app = SholatGUI(root)
    root.mainloop()